language: scala

jdk: openjdk11

scala:
  - 2.12.12
  - 2.13.5

branches:
  only:
    - master

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.sbt -name "*.lock" -type f -delete

cache:
  directories:
    - $HOME/google-cloud-sdk
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

install:
  - pip install --user codecov

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport scalafmtCheckAll test:scalafmtCheck scalafmtSbtCheck && codecov
